### ISSUE TITLE
AzTs configuration in Azure DevOps pipeline

### ISSUE THREAD

**Issue by AshishNigamNoida** [azsk/AzTS-docs#114]
Hi Team,

Is there any way that we can AzTs for static code(ARM , Terraform files) analysis in Azure DevOps build pipeline? Currently we are using AzSk for this analysis.

So If yes then please share the steps we need to follow to configure in our Azure DevOps pipeline.

Regards,
Ashish

**Comment by pranchalsomani** [comment]
No currently AzTS is not supported in DevOps pipelines

**Comment by gvaradarajan-msft** [comment]
Since there has not been any discussion here for over a month, this issue is being closed. @AshishNigamNoida - please create a new issue for any other queries you may have. Thank you!

@pranchalsomani - FYI.
