### ISSUE TITLE
Suggested patch to function SendCustomAIEvent in AzTSSetup.ps1

### ISSUE THREAD

**Issue by ergihu** [azsk/AzTS-docs#23]
I would kindly like to suggest a modification to the file AzTSSetup.ps1 that is part of the AzTS solution. I’d submit a proper pull request, but the file AzTSSetup.ps1 is only visible to me within the zip file https://github.com/azsk/AzTS-docs/blob/main/TemplateFiles/DeploymentFiles.zip.

Currently on line 543 there is the following:
            $AssemblyPath = Get-ChildItem -Path "$($env:USERPROFILE)\Documents\WindowsPowerShell\Modules\Az.Accounts" -Filter "Microsoft.ApplicationInsights.dll" -Recurse

I suggest that it should be changed to this:
            $AssemblyPath = Get-ChildItem -Path (Get-Item (Get-Module Az.Accounts).Path).DirectoryName -Filter "Microsoft.ApplicationInsights.dll" -Recurse

This finds the path where the currently loaded module Az.Accounts was actually loaded from, instead of looking for the module only under $env:USERPROFILE in a hard-coded subdirectory.

**Comment by SINIKI** [comment]
@ergihu:

Thank you for your feedback!
We will be incorporating the requested update in our upcoming sprints.

**Comment by SINIKI** [comment]
Closing this thread as this fix has been released.
