### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by maikvandergaag** [azsk/AzTS-docs#233]
After configuring a custom url and adding the redirect url to the correct application we receive below error:

![image](https://user-images.githubusercontent.com/9531411/171281170-c91251e0-17f5-41e8-ac87-cdd1074d6add.png)

**Comment by MSFT-Chirag** [comment]
Hi @maikvandergaag, 
Could you paste the error in the console for our reference ?

**Comment by maikvandergaag** [comment]
@MSFT-Chirag: What do you mean?

**Comment by Aboli-msft** [comment]
Hello, closing this issue as it has been a while we did not hear back. Please feel free to reach out to us at [aztssup@microsoft.com](mailto:aztssup@microsoft.com) in case issue still exists or any other questions.
