### ISSUE TITLE
Load errors into Power BI dashboard

### ISSUE THREAD

**Issue by pasasorin** [azsk/AzTS-docs#240]
When trying to load the data into PowerBI, everything works for the "TenantSecurityReport" template, but for the "TenantSecurityInventoryReport" I receive many errors like the ones below:

_Loading blocked by failures with other queries._

_Web.Contents failed to get contents from 'https://api.loganalytics.io/v1/workspaces/0000000000000000000000/query?query=let%20LatestJobId%20%3D%20toscalar%20%28%20AzSK_SecureScoreControls_CL%20%7C%20where%20TimeGenerated%20%3E%20ago%281d%29%20%7C%20summarize%20arg_max%28JobId_d%2C%2A%29%7C%20project%20%20JobId_d%29%3B%0AAzSK_SecureScoreControls_CL%0A%7C%20where%20JobId_d%20%3D%3D%20LatestJobId%0A%7C%20summarize%20arg_max%28TimeGenerated%2C%20%2A%29%20by%20Id_s%0A%7C%20summarize%20count%28%29%20by%20CollectionTime%20%3D%20bin%28TimeGenerated%2C15s%29&x-ms-app=OmsAnalyticsPBI&prefer=ai.response-thinning%3Dtrue' (400): Bad Request_

There is already an issue opened (and closed ???, but with no resolution) about this problem: https://github.com/azsk/AzTS-docs/issues/122

Thanks!

**Comment by Aboli-msft** [comment]
Hi @pasasorin, thank you for trying out AzTS. Can you please confirm if both TenantSecurityReport template and TenantSecurityInventoryReport template are pointing to the same Log Analytics Workspace (Same WorkspaceId provided while loading data into both the templates)? If yes, can you please try running couple of Log analytics queries from inventory template and see if data is present?

**Comment by Aboli-msft** [comment]
If you are trying for scheduled refresh, please check whether Log Anlytics workspace Id is replaced for all queries (a[4] step from [here](https://github.com/azsk/AzTS-docs/tree/main/02-Monitoring%20security%20using%20AzTS#step-4-publish-the-powerbi-report-to-your-enterprise-powerbi-workspace)). Please let us know if this helps.

**Comment by pasasorin** [comment]
@Aboli-msft thank you for your answer, the templates are pointing to the same LA workspace. It seems that most of the issues come from the fact that tables are missing (like, for example, the table "AzSK_SecureScore_CL" or "AzSK_SSAssessmentAdditionalMetaData_CL"). Any idea why this might have happened?

**Comment by Aboli-msft** [comment]
Can you please check if Microsoft Defender for Cloud is enabled for subscriptions getting scanned via AzTS setup?

**Comment by pasasorin** [comment]
You are correct, it is not enabled. I am working in my Visual Studio Enterprise subscription, and I have not enabled Defender. 
Thank you for your support!
