### ISSUE TITLE
Multi Tenant Subscriptions not loading in UI

### ISSUE THREAD

**Issue by Tianreagon** [azsk/AzTS-docs#244]
I have installed and configured AzTS as a multi-tenant scanner, using a central MI with Active Directory. I followed the instructions here: [instructions](https://github.com/azsk/AzTS-docs/blob/main/05-Cross-tenant%20subscription%20scan/MultiTenantSetupWithAADApp.md/#1-steps-to-install-multi-tenant-azts-solution)

I then onboarded multiple tenant subscriptions for scanning. One of which is the subscription on which AzTS is installed. All the relevant data is being loaded into the storage bucket and log analytics, so the subscriptions of each tenant are being scanned correctly. However, when anyone logs in to the UI, they can not see any of the scan data or subscription data from any of the tenants except the one on which AzTS is installed. Only that subscription is listed in the dashboard with its scan data, none of the other onboarded tenants.
I followed the appropriate API steps for onboarding and when I do an API call to check the subscription statuses it returns as enabled. 
I also made sure that whoever is logging in to the UI has the permissions in Azure AD on each tenant account to see the relevant tenant subscriptions listed.

One other thing that could be of help, is when I do an API call for onboarding or getting tenant details, the request goes through successfully. However, when I do an API call for getting compliance status or requesting a scan it returns this message, even on the subscription that AzTS is installed on and shows in the dashboard:

`Could not find any subscription against your login. Please validate, you have [ Owner, Contributor, ServiceAdministrator, CoAdministrator, AccountAdministrator, Security Reader, Security Admin, CSEO DevOps Role, SCIM DevOps Role]  access on subscriptions`

I am a owner and contributor on the subscription and in Azure AD, I am a global admin and privileged admin.
What could the issue be, any help would be highly appreciated as I have been struggling with this for a while now.

**Comment by vinodsunkara** [comment]
We are also facing the same issue. 
Could anyone please help us to fix the problem? Attached is the screenshot for reference. 

![image](https://user-images.githubusercontent.com/37222937/177843253-c3afb5eb-0fa5-481d-b7dd-1f2331426cde.png)

**Comment by Aboli-msft** [comment]
Hi Tian, We had call and mail thread for this issue and provided insights on this issue. To summarize, once, we have AzTS installed in a subscription and have native users (users created in that tenant) given access to the subscriptions in that tenant, then we can proceed to invite these native users as guest users to another tenant. These guest users (guest to the other tenant and not the host tenant) should be then given appropriate access to subscriptions in that tenant. Closing thread here.  Please feel free to reach out again if needed
