### ISSUE TITLE
video about AzTS?

### ISSUE THREAD

**Issue by cheahengsoon** [azsk/AzTS-docs#26]
Hi Team,

Any video or tutorial or slide  about AzTS ?

**Comment by SINIKI** [comment]
Hello @cheahengsoon, thank you for contacting us. Can you please elaborate on the topic you are looking tutorial video for?
You can find tutorial videos for AzTS UI [here](https://github.com/azsk/AzTS-docs/tree/main/03-Running%20AzTS%20solution%20from%20UI).

**Comment by pranchalsomani** [comment]
It’s been a long time since we have heard from you. So closing this issue and in case you need any help please reach out to us.
