### ISSUE TITLE
Scan on sub is taking time to complete

### ISSUE THREAD

**Issue by v-mosha** [azsk/AzTS-docs#276]
Hi All, 

We have submitted scan for our subscription but it is taking more time to complete. Also, we are unable to find number of controls passed or failed. 

Kindly look into the issue. Thanks.

![AzTs_Scan](https://user-images.githubusercontent.com/116194235/197766944-2cbd1415-4614-463e-bb48-7d71a6e03d84.jpg)

**Comment by aakashpahwa-msft** [comment]
As discussed, the issue was resolved as it was a transient error.
