### ISSUE TITLE
Faild status for control Azure_KeyVault_Audit_Enable_Diagnostics_Log

### ISSUE THREAD

**Issue by Nickteekw** [azsk/AzTS-docs#298]
Hi there, 

I'd like to thank the team in getting this scanner made available publicly and it has since helped me a lot. 

I'm seeking feedback from the team as I'm getting a failed status for this control `Azure_KeyVault_Audit_Enable_Diagnostics_Log` in AzTs Tenant scanner despite I have the diagnostic setting enabled for my key vault. 

Is there something else I have missed? 

Regards,
Nick

**Comment by Nickteekw** [comment]
Hi Asim, 

Thanks for the getting back to me. And yes, I'm getting the failure status on the UI despite the diagnostic setting enabled for my key vault.

**Comment by asimks** [comment]
Hi Nick,

Kindly share the status reason here, so that we could help you out with the issue.

Regards,
Asim

**Comment by Nickteekw** [comment]
HI Asim, 
Apology, the status reason is `Diagnostics setting is disabled for resource`, despite I have either law or law and storage attached in the diagnostic setting.


<img width="1007" alt="Screenshot 2022-12-16 090213" src="https://user-images.githubusercontent.com/39953777/207977479-14112820-4ca8-4e6a-bd98-eb2b021103ce.png">

<img width="942" alt="Screenshot 2022-12-16 085823" src="https://user-images.githubusercontent.com/39953777/207977960-2bbf3160-142e-4365-b6ab-5e20cc014969.png">


Thanks for your time again. 

Regards,
Nick

**Comment by asimks** [comment]
Hi Nick,
Sorry for the delay in response due to holiday season. 
We have identified the issue in the control logic due to which you are getting this control flagged as failed.
We are working to get this resolved. 
We follow a monthly external release schedule, so you could expect the fix by January end.
Thanks for bringing this to our attention.

Regards,
Asim

**Comment by Nickteekw** [comment]
> Hi @Nickteekw , Sorry for the delay in response due to holiday season. We have identified the issue in the control logic due to which you are getting this control flagged as failed. We are working to get this resolved. We follow a monthly external release schedule, so you could expect the fix by January end. Thanks for bringing this to our attention.
> 
> Regards, Asim

Thanks @asimks Really appreciate your time on this.

**Comment by asimks** [comment]
Hi @Nickteekw ,
We have released the fix for the issue pointed by you.
You could validate and confirm the same at your end.
Feel free to revert back in case the issue still persists for you.

Regards,
Asim
