### ISSUE TITLE
Deploying in multiapp not onboarding 

### ISSUE THREAD

**Issue by albandrod** [azsk/AzTS-docs#316]
I have following all the several steps in order to create the app, give permissions an son on, finally i use postman to onboard the sub, which gave me a 200 Ok, but after waiting 72h, i cannot see anything in the UI app. What's going wrong? Is it possible to have a log or something like that to dig deeper?

**Comment by vaishnavipulluri** [comment]
Hi @albandrod,

As a first step please verify the solution installation is complete following steps [here](https://github.com/azsk/AzTS-docs/blob/main/01-Setup%20and%20getting%20started/README.md#3-verifying-that-tenant-security-solution-installation-is-complete) and then you should be able to verify the logs similar to this [section](https://github.com/azsk/AzTS-docs/blob/main/01-Setup%20and%20getting%20started/README.md#4-log-analytics-visualization).

If there is no issue with above, you should be able to load the AzTS UI app with appropriate results. 

_Note:_ 

Below, the tenant where AzTS Setup is done is referred to as _Host Tenant_ and other tenants onboarded onto AzTS solution in host tenant are referred to as _Guest Tenants_.

In case you are looking for scan results on subscriptions present in Guest Tenants, proceed to invite the user as Guest User to Guest Tenant and provide appropriate access to subscriptions in that Guest Tenant. This should load scan results for the subscriptions in the Guest Tenants.

We can setup a call and investigate in case you are still facing the issue. Please feel free to reach out again if needed.
