### ISSUE TITLE
Setup self-attestation feature

### ISSUE THREAD

**Issue by TitleistProV1** [azsk/AzTS-docs#342]
When I execute the Enable-ByDesignExceptionFeature, using the settings specified, I get the following error: 

Enable-ByDesignExceptionFeature : The term 'Enable-ByDesignExceptionFeature' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At line:1 char:1
+ Enable-ByDesignExceptionFeature `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Enable-ByDesignExceptionFeature:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by aakashpahwa-msft** [comment]
Hi @TitleistProV1,
Can you confirm the successful running of the prerequisite commands (Step 1 to 3) from [here](https://github.com/azsk/AzTS-docs/blob/main/10-Security%20Exceptions/SelfAttestation.md#step-1-of-4-validate-prerequisites-on-machine).
And please make sure you're loading the functions properly (i.e. Step 3.d.).

**Comment by TitleistProV1** [comment]
I recreated a shell and started from scratch. I have gotten father than previously. However, the "Connect-AzureAD" cmdlet has been deprecated and you have to connect to Azure AD via the "Connect-MgGraph" cmdlet. When I do that and rune the "Enable-ByDesignExceptionFeature" command, I now get an error, "Failed to validate AzTS host resource group."

**Comment by Aboli-msft** [comment]
Hi @TitleistProV1, Could you please confirm if you are using user account context in PowerShell session? If you could provide detailed error log along with executed commands, it would help us to investigate further. We can also setup a call and investigate in case needed. Please feel free to reach out to us on aztssup@microsoft.com.

**Comment by asimks** [comment]
Hi @TitleistProV1, could you please confirm if you are still facing the above issue, or it has been resolved.
