### ISSUE TITLE
UI client secret expired

### ISSUE THREAD

**Issue by mr3429** [azsk/AzTS-docs#391]
Hi,
We have an issue with our implementation of AzTS in that when loading the UI we get the error “Compliance summary not available.”
Network logs show that there is a 404 when sending a  POST to the webapi endpoint /subscription/SubscriptionComplianceSummary.

Additionally, in the AutoUpdater logs there is an exception saying that the secret for the UI has expired. I'm not sure if this is related.
I can see that the app registration secret has expired but not sure what needs to be done if it is manually renewed.

Lastly, the aztssup@microsoft.com address is bouncing :)

Thanks.

**Comment by asimks** [comment]
Hi @mr3429 
Thanks for showing interest in AzTS.
Could you help me with few details:
1) Is this a new setup or an old setup which was previously working fine and started to fail off late.
2) If it's a new setup, could you share the installation logs, which will help us to identify any installation related issue.
3)Would request you to also verify the list of resources created for new installation from [here](https://github.com/azsk/AzTS-docs/tree/main/01-Setup%20and%20getting%20started#step-1-of-3-verify-resources-created-as-part-of-setup).
4) Would also request you to access the Application insights created for AzTS and give us a dump of exceptions from there after trying to access AzTS UI, which will help us to know the exact issue around the time interval of the failure.

@asimks

**Comment by mr3429** [comment]
Hi asimks,

This installation has been working for several months now, all resources were created successfully.
There are several errors but none when we actually try to login to the UI.

Here are some:
13/10/2023, 07:01:01
Response status code does not indicate success: 400 (Bad Request).
Problem Id:System.Net.Http.HttpRequestException at Microsoft.AzSK.ATS.Extensions.Storage.LAStorageProvider.Get


13/10/2023, 07:01:03
One or more errors occurred. (A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details. Original exception: AADSTS7000222: The provided client secret keys for app 'xxx' are expired.
...
at Microsoft.AzSK.ATS.ProcessSubscriptions.Processors.ControlEvaluationProcessor.Process(SubscriptionInventory subscriptionInventory) in D:\a\1\s\src\TenantScan\ProcessSubPolicySummary\Processors\ControlProcessors\ControlEvaluationProcessor.cs:line 274] 


13/10/2023, 08:01:06
Exception has been thrown by the target of an invocation.
Problem Id:System.ArgumentException at System.Version.ParseVersion
Exception has been thrown by the target of an invocation. Version string portion was too short or too long. (Parameter 'input')

**Comment by asimks** [comment]
Hi @mr3429 ,/
Could you also help us with few more details.
1) Is the setup single tenant or multi-tenant setup.
2) Have you enabled self-attestation feature for your setup.

Once we have answer to above queries, we would be able to help you better. 
In case even after having above details the reason for the issue is not clear, we could have a call to look into the issue faced by you.
We work in IST from 9 AM to 6 PM.

**Comment by mr3429** [comment]
Hello,

Thanks for the reply.

This is a single tenant setup and we have enabled self-attestation.
Additionally since the private link feature was not working we have introduced some inbound access restrictions for the functions and apps, though they are all accessible to each other.

Kind Regards,

Matt Rigby
Cloud Native Engineer, Digital, Data & Cloud

***@***.***   ***@***.***

Fujitsu
7th Floor, The Lantern, 75 Hampstead Rd, London NW1 2PL
M           +44 7867835135
E             ***@***.******@***.***>
W           fujitsu.com<http://www.fujitsu.com/>

[Ein Bild, das Text, ClipArt enthält.  Automatisch generierte Beschreibung]<https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2FFujitsuICT>  [Ein Bild, das Text enthält.  Automatisch generierte Beschreibung] <https://twitter.com/Fujitsu_Global>   [Ein Bild, das Text, ClipArt enthält.  Automatisch generierte Beschreibung] <https://www.youtube.com/c/Fujitsu>   [Ein Bild, das Text enthält.  Automatisch generierte Beschreibung] <https://corporate-blog.global.fujitsu.com/fgb/>   ***@***.*** <https://www.linkedin.com/authwall?trk=bf&trkInfo=AQGWhlce9gFH5gAAAX0UIod4_UR5Do_5ss3a_2f1TbkSl3VAS8JMlJuJyqFeTjQ7ooreQUVW2eLPdxHpdzldp22a-oJtfvo103-7_zPiUAmWx1D7vTBjoR1XkeJkGyBBnP18cIM=&originalReferer=&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Ffujitsu>
