### ISSUE TITLE
Allow directory switching

### ISSUE THREAD

**Issue by brwalkerM** [azsk/AzTS-docs#394]
Service360 Notifications <s360notf@microsoft.com> is sending issues via email. However, the https://dst-azts.azurewebsites.net/ website that is supposed to host the remediation scripts doesn't allow me access (or the ability to switch to the directory that hosts the issues). I don't have any subscriptions in the @microsoft tenant so I get the error "
Access required.
Please verify that you have the required access [ Owner, Contributor, ServiceAdministrator, CoAdministrator, AccountAdministrator, Security Reader, Security Admin, CSEO DevOps Role, SCIM DevOps Role] over the subscriptions for which you want to view Compliance Summary."

**Comment by Loo-Ree** [comment]
> Service360 Notifications [s360notf@microsoft.com](mailto:s360notf@microsoft.com) is sending issues via email. However, the https://dst-azts.azurewebsites.net/ website that is supposed to host the remediation scripts doesn't allow me access (or the ability to switch to the directory that hosts the issues). I don't have any subscriptions in the @microsoft tenant so I get the error " Access required. Please verify that you have the required access [ Owner, Contributor, ServiceAdministrator, CoAdministrator, AccountAdministrator, Security Reader, Security Admin, CSEO DevOps Role, SCIM DevOps Role] over the subscriptions for which you want to view Compliance Summary."

I have the very same problem.

**Comment by pranchalsomani** [comment]
Hey @Loo-Ree. Please reach out to us on : aztssup@microsoft.com
