### ISSUE TITLE
Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions

### ISSUE THREAD

**Issue by uzma-k** [azsk/AzTS-docs#397]
I am running the  Invoke-AzureScan commant and getting below error 
Invoke-AzureScan: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (0x80131621)
![image](https://github.com/azsk/AzTS-docs/assets/78472998/7dd9e867-094c-4596-b0e7-21c4c4df55a7)

**Comment by uzma-k** [comment]
This issue was resolved by Installing the lower version of .net framework. But now by scan are failing withoug any logs with below error
Invoke-AzureScan: Could not find a part of the path 'C:\Users\xxxxx\AppData\Local\LocalScan\Microsoft\AzTSLogs\Sub_xxxxxxx\20232712_11_22_09_IAS\Errorlogs'.
Note: There is no log file in this location.

**Comment by Aboli-msft** [comment]
Hi @uzma-k , Could you please share screenshot with latest error details?

**Comment by uzma-k** [comment]
There was no error, but it resolved after I installed the Azure CLI manually. Its working now. Thanks.
