### ISSUE TITLE
AzTS dashboard is not loading

### ISSUE THREAD

**Issue by v-mosha** [azsk/AzTS-docs#420]
AzTS dashboard is not loading, getting error 
![AzTs_Down](https://github.com/azsk/AzTS-docs/assets/116194235/b0437ba1-bec5-48d7-84fd-caa45863bc94)

**Comment by TarunKrShukla** [comment]
Hi @v-mosha ,

Are you facing this issue consistently? Also, looks like you are an internal Microsoft user. GitHub is for external users only. Please ping me over teams or shoot an email to me directly.

Thanks,
Tarun

**Comment by pranchalsomani** [comment]
Closing this issue. Please feel free to reopen if you have any further questions or comments.
