### ISSUE TITLE
Source code for the MMA Removal tool function app

### ISSUE THREAD

**Issue by giraudeo** [azsk/AzTS-docs#421]
Hello,

I see the function apps of the MMA Removal tool rely on external packages stored at "https://aka.ms/AzTS/MMARemovalUtility/*".

Looking to the content, it's compiled code.

Is it possible to have access to the source code to evaluate what each function is doing?

(Main reason is to comply to my company Security policy).

Regards,

**Comment by pranchalsomani** [comment]
Closing this issue. Please feel free to reopen if you have any further questions or comments.

**Comment by giraudeo** [comment]
Hello,

I sent an email but got a "couldn't be delivered" reply with error:
"The group ssengteam only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list."

Any advise?

Regards,

**Comment by giraudeo** [comment]
@TarunKrShukla @pranchalsomani Hello,

I did send an email to "aztssup@microsoft.com" but got a "Undeliverable" message back:
"The group ssengteam only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list."

Could you help?

Regards,
