### ISSUE TITLE
Typo in the function "Update-AzTSMMARemovalUtilityDiscoveryTrigger" in MMARemovalUtilitySetup.ps1

### ISSUE THREAD

**Issue by fyankov96** [azsk/AzTS-docs#428]
There is a typo and a mismatch with the provided documentation in the name of the passed parameters in the Update-AzTSMMARemovalUtilityDiscoveryTrigger function located within the MMARemovalUtilitySetup.ps1 script which is part of the MMA Removal Utility.

The typo is in StartScopeResolverImmediatley and StartExtensionDiscoveryImmediatley , which should be StartScopeResolverImmediately and StartExtensionDiscoveryImmediately respectively.

**Comment by dassayantan1** [comment]
Hi,
Thanks for reaching out!
We are looking into it and we'll get back to you once we have an update on this.

**Comment by vaishnavipulluri** [comment]
Hello,

Thanks for reporting this.

We have worked on the required enhancements to address any such issues.
