### ISSUE TITLE
Cannot reach aztssup contact email

### ISSUE THREAD

**Issue by giraudeo** [azsk/AzTS-docs#432]
Hello,

I sent an email to "[aztssup@microsoft.com](mailto:aztssup@microsoft.com)" but got a "Couldn't be delivered" message back:
"The group ssengteam only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list."

Could you help?

Regards,

**Comment by v-rahkuma** [comment]
Hello,

Kindly reach out to us on this email azsksup@microsoft.com .

Thank you
