### ISSUE TITLE
 Cannot reach azsksup contact email

### ISSUE THREAD

**Issue by giraudeo** [azsk/AzTS-docs#433]
Hello,

I sent an email to "azsksup@microsoft.com" but got a "Delivery has failed to these recipients or groups" message back:
"Your message couldn't be delivered because delivery to this group is restricted to authenticated senders. If the problem continues, please contact your email admin."

Could you help?

Regards,

**Comment by v-rahkuma** [comment]
Hi,

Acknowledge the request. Please allow us some time to look into it and get back to you.

**Comment by vaishnavipulluri** [comment]
Hello,

The issue has been fixed now. Please let us know if you are facing any further issues.
