### ISSUE TITLE
AzTs Dashboard is not loading since the evening

### ISSUE THREAD

**Issue by v-moalib** [azsk/AzTS-docs#440]
We are encountering an error when trying to access the AzTS dashboard. Please investigate the issue.
<img width="898" alt="Screenshot 2024-05-11 031458" src="https://github.com/azsk/AzTS-docs/assets/47417673/cb3ddc17-3265-4428-a453-d88543fe986a">

**Comment by rajatgoyalMS** [comment]
Hi @v-moalib,
We were observing performance degradation (service health issue from Azure side) with our data store due to which intermittently calls are getting timed out resulting in AZTS UI failure. We are already working with Azure support team to fix this issue.

Thanks

**Comment by Aboli-msft** [comment]
Hi @v-moalib, please let us know if you are still facing issue. It seems Azure side issue is resolved now.
