### ISSUE TITLE
I can see some subscriptions but not all

### ISSUE THREAD

**Issue by devwheel** [azsk/AzTS-docs#444]
I am an owner of 2 subscriptions, but I only see one of them.  
Where do I look to solve that?

**Comment by Aboli-msft** [comment]
Hi @devwheel, Is this same issue for which you have reached out to us over IcM? If not, requesting details like whether issue is persistent, is there any change in role assignments you have over those subscriptions? Please let us know further

**Comment by Aboli-msft** [comment]
Hi @devwheel , awaiting response on this

**Comment by Aboli-msft** [comment]
Closing this issue. Please let us know in case you need further help
