### ISSUE TITLE
Enforcement Page Not Available

### ISSUE THREAD

**Issue by JosephAlina1** [azsk/AzTS-docs#449]
I am not seeing any information in the site. This link is Blank: https://securityscanningservices.microsoft.com/policies/enforcement

**Comment by dassayantan1** [comment]
Acknowledging the issue, we'll get back to you on this

**Comment by aakashpahwa-msft** [comment]
Closing this issue as this is an internal query. Reached out to user and shifted to an appropriate way of tracking this internal issue.
