### ISSUE TITLE
Cannot Access

### ISSUE THREAD

**Issue by llowevad** [azsk/AzTS-docs#451]
I am getting Access Denied when going to scan my subscriptions... how can i get around this...

![image](https://github.com/azsk/AzTS-docs/assets/8823690/947c6225-5b0a-4942-bf1d-35844cf2794a)

**Comment by Aboli-msft** [comment]
Hi @llowevad , apologies for delayed response. Are you still facing this issue? Please note that subscriptions that show up on the AzTS UI depend on the kind of Azure access you have on those.

‘Compliance visibility is based on your access ("Owner", "Contributor", "ServiceAdministrator", "CoAdministrator", "AccountAdministrator", "Security Admin", "Security Reader") at subscription or resource group(s) level.’

Please ensure you have one of these roles on at least one of the subscriptions/Resource Groups covered as part of AzTS instance. Once you have required access, it will take next 24 hours to get reflected in AzTS UI

**Comment by Aboli-msft** [comment]
Hi @llowevad , please let us know if above comment helps or you are still facing the issue.

**Comment by Aboli-msft** [comment]
Hi @llowevad , Closing this issue as we did not hear back. Please feel free to reopen in case you are still facing issue
