### ISSUE TITLE
Failed check for "NSG must be configured for Virtual Machine" caused by "OffByPolicy"

### ISSUE THREAD

**Issue by humblejay** [azsk/AzTS-docs#459]
The confidential VM which triggers this failed check has NSG associated with both the NIC and the subnet,  the scanning tool is showing following error.   

```
{"Message": "Validated control status through MDC assessment", "SecurityAssessmentStatus": {"ResourceName": "vm-cvm5066", "StatusMessage": {
  "code": "NotApplicable",
  "cause": "OffByPolicy",
  "description": "The recommendation is disabled in policy"
}  } }
Disabling or exempting the policy from getting evaluated is not recommended. The Control will be marked as Failed.
```

Also there is no such policy assigned to the VM itself, which is odd.

**Comment by vaishnavipulluri** [comment]
Hello @humblejay, Can you please reach out to us on azsksup@microsoft.com with resource specific details?

**Comment by vaishnavipulluri** [comment]
@humblejay, Closing this issue as we did not hear back. Please reach out to the above mentioned email with resource specific details if you still facing the issue.
