### ISSUE TITLE
Exception required for "Required guest configuration extension is missing in VM"  check with Azure Confidential VM

### ISSUE THREAD

**Issue by humblejay** [azsk/AzTS-docs#460]
The check fails with error "Required guest configuration extension is missing in VM. Required provisioningState of guest extension should be 'Succeeded'"   

This is because the extension is not compatible with Azure Confidential VM's.  We need an exception for this check for Azure Confidential VMs.

**Comment by vaishnavipulluri** [comment]
@humblejay, Closing this issue as we did not hear back. Please reach out to the above mentioned email with resource specific details if you still facing the issue.
