### ISSUE TITLE
Cannot view compliance in AzTS after activating PIM permission

### ISSUE THREAD

**Issue by hannwang1** [azsk/AzTS-docs#467]
Right now I have persistent access to my Azure subscription with classic service admin role.  So I am able to use AzTS to perform ad-hoc scan on my subscription to detect issues and verify my fix.   New S360 KPI requires classic admin role to be removed and replaced with PIM permission by Aug 30 as classic admin role will be removed from Azure after Aug 30.  But none can access AzTS to see the subscription after activating the PIM subscription permission.  I see the message "**You might not be able to view the compliance for some of your subscriptions due to ongoing issues with the PIM RBAC APIs. We are working to resolve this as soon as possible**" has been posted in AzTS page for a very very long time.  Can you please provide ETA for the fix of this issue?  Are you aware of that persistent access to Azure subscription is not allowed anymore and classic admin role will be removed from Azure after Aug 30?  After that, none can access to AzTS and your online service will be simply no use anymore. 

 
![image](https://github.com/user-attachments/assets/b17c8338-cf34-4e1a-9870-ce3875dab1a6)

**Comment by v-rahkuma** [comment]
Hello hannwang1,
 
Thank you for your message. Could you please confirm if you are still experiencing the issue? If yes, kindly reach out to us at **azsksup@microsoft.com** for further assistance.
 
Thank you!
