### ISSUE TITLE
RBAC access

### ISSUE THREAD

**Issue by prasad-metkar** [azsk/AzTS-docs#474]
When AZTS tool is doing the scans, it is taking the RBAC snapshot and using it to filter the results on AZTS web portal.
 
Many of our team members have PIM assignments as contributors on subscription but they haven't activated their permissions when the audit jobs are running. so on UI, they are not seeing their subscription.
 
Is their a way to change this behavior? we would like to use their PIM assignment eligibility data than actual RBAC data.

**Comment by jaiswalricha** [comment]
Hi @prasad-metkar ,

Please check if below link helps, Point 2 cover steps to consider PIM assignments. 

https://github.com/azsk/AzTS-docs/tree/main/FAQs#troubleshooting-steps
