### ISSUE TITLE
New control - Azure policy

### ISSUE THREAD

**Issue by prasad-metkar** [azsk/AzTS-docs#475]
Hello,

We have created a new control using Azure policy, but it's not working. We followed the same steps given in the AzTS documentation.
https://github.com/azsk/AzTS-docs/blob/main/06-Customizing%20AzTS%20for%20your%20org/Extending%20AzTS/AddControlForPolicy.md

**Comment by rajatgoyalMS** [comment]
Hi Prasad,
Details regarding this issue has already been shared over mail.

Thanks.
Rajat Goyal
