### ISSUE TITLE
AzTS UI returns 404 when accessing it

### ISSUE THREAD

**Issue by bmvalente** [azsk/AzTS-docs#48]
After setting up the solution and running the all the steps in the setup page, even after waiting over 2 hours, when accessing the UI app it returns a blank page. In Application insights I can see a 404 being returned.

**Comment by MSFT-Chirag** [comment]
Hey @bmvalente,
Thanks for bringing this to our attention. We are looking into this.
Please let us know if you still face this issue.

**Comment by MSFT-Chirag** [comment]
Hey @bmvalente,
We have verified the solution setup at our end. If you are still facing the issue, please try reinstalling the solution.
If the issue persists, please contact us at: azsksup@microsoft.com. We would love to help you resolve this issue.

**Comment by pranchalsomani** [comment]
It’s been a long time since we have heard from you. So closing this issue and in case you need any help Please reach out to us.
