### ISSUE TITLE
How to completely remove AzTs from the subscription/tenant

### ISSUE THREAD

**Issue by DImaste** [azsk/AzTS-docs#64]
I tried to remove it manually (by removing RG and MI), but when I started the new installation, the web UI component was not installed. However, there weren't any errors. I suppose there might be services that I didn't remove last time.

**Comment by MSFT-Chirag** [comment]
Hey @DImaste,
Please make sure you are passing the [-EnableAzTSUI] flag while deploying. 
Please feel free to contact us at azsksup@microsoft.com.
